"""
Django settings for ragstar_django project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os  # Import os for environment variables
import sys  # Add this line

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add the 'apps' directory to the Python path
# Add these lines
sys.path.insert(0, str(BASE_DIR / "apps"))
# --- End of Added Lines ---


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-i7l&cnk2eemm1e!13kew37c=ctkpa2!0ufw)v&9vlwzqolq(y="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["midge-helping-socially.ngrok-free.app", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "pgvector.django",
    # Use full AppConfig paths
    "apps.core.apps.CoreConfig",
    "apps.data_sources.apps.DataSourcesConfig",
    "apps.knowledge_base.apps.KnowledgeBaseConfig",
    "apps.embeddings.apps.EmbeddingsConfig",
    "apps.llm_providers.apps.LlmProvidersConfig",
    "apps.workflows.apps.WorkflowsConfig",
    "apps.integrations.apps.IntegrationsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ragstar.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ragstar.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "ragstar_django"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "password"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- Ragstar / LLM Settings ---

# API Key - loaded from environment variable primarily
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

# Default model names (can be overridden by environment variables if needed)
LLM_CHAT_MODEL = os.environ.get("LLM_CHAT_MODEL", "gpt-4o-mini")
LLM_EMBEDDING_MODEL = os.environ.get("LLM_EMBEDDING_MODEL", "text-embedding-3-small")

# Optional: Add other LLM provider keys here
# ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
# LLM_PROVIDER = os.environ.get("LLM_PROVIDER", "openai") # To switch between providers

# --- Logging Configuration ---
# Add this towards the end of your settings.py file
# (After other settings like DATABASES, OPENAI_API_KEY, etc.)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # Keep Django's default loggers
    "formatters": {
        "verbose": {
            # Include timestamp, level, logger name, and message
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "colored": {  # Add this formatter
            "()": "coloredlogs.ColoredFormatter",
            # Updated format string for better readability
            "format": "%(asctime)s [%(levelname)-8s] %(name)s:%(funcName)s:%(lineno)d - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
            "field_styles": {
                "asctime": {"color": "green"},
                "hostname": {"color": "magenta"},
                "levelname": {"color": "black", "bold": True},
                "name": {"color": "blue"},
                "programname": {"color": "cyan"},
                "username": {"color": "yellow"},
                # Add styles for new fields if desired
                "funcName": {"color": "cyan"},
                "lineno": {"color": "magenta"},
            },
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",  # Handler processes all messages DEBUG and above
            "class": "logging.StreamHandler",
            "formatter": "colored",  # Change this from 'verbose' to 'colored'
        },
    },
    "loggers": {
        "": {  # Root logger - controls default level via runserver -v
            "handlers": ["console"],
            # Level is typically set by Django based on DEBUG and -v flags.
            # Setting INFO here provides a sensible default if not overridden.
            # -v 0 -> WARNING, -v 1 -> INFO, -v 2/3 -> DEBUG
        },
        "django": {  # Control Django framework logs
            "handlers": ["console"],
            "level": "INFO",  # Avoid excessive Django internal logs unless needed
            "propagate": False,  # Don't pass to root logger
        },
        "django.request": {  # Specific handler for request errors
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.db.backends": {  # Control SQL query logging
            "handlers": ["console"],
            # Set to INFO to suppress SQL logs by default.
            # Django might set this to DEBUG automatically with runserver -v 3
            "level": "INFO",
            "propagate": False,
        },
        "core": {  # Logger for your 'core' application
            "handlers": ["console"],
            # IMPORTANT: Set level to DEBUG so core's debug messages are
            # always passed to the handler, regardless of root logger level.
            "level": "DEBUG",
            "propagate": False,  # Don't pass core messages to root logger
        },
        "apps.workflows": {  # Logger for the workflows app
            "handlers": ["console"],
            "level": "DEBUG",  # Capture DEBUG level messages from workflows
            "propagate": False,  # Don't pass to root logger
        },
    },
}

# --- Custom Settings ---

# Verbosity level for Agents triggered via Admin actions
# 0 = WARNING/ERROR, 1 = INFO, 3 = DEBUG
AGENT_DEFAULT_VERBOSITY = 3
