# Generated by Django 5.2 on 2025-05-01 10:21

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        # Removed CreateModel for Model
        # Removed CreateModel for ModelEmbedding
        # Removed CreateModel for Question
        # Removed CreateModel for QuestionModel
        # Removed AddField for question.models_used
        # Keep VectorExtension if core app requires it independently,
        # otherwise this migration might become empty or just contain VectorExtension.
    ]
