"""Add feedback_embedding to questions table

Revision ID: 865a53a7440e
Revises: cbb70bad3492
Create Date: 2025-04-07 11:19:15.027461

"""

from typing import Sequence, Union
import logging

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

from ragstar.utils.logging import get_logger

# Get logger
logger = get_logger(__name__)

# revision identifiers, used by Alembic.
revision: str = "865a53a7440e"
down_revision: Union[str, None] = "cbb70bad3492"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    logger.info(f"Starting Add feedback_embedding to questions table upgrade")

    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index only if it exists to avoid errors if already missing
    op.execute("DROP INDEX IF EXISTS checkpoint_writes_thread_id_idx;")
    op.execute("DROP TABLE IF EXISTS checkpoint_writes CASCADE;")
    op.execute("DROP TABLE IF EXISTS checkpoint_migrations CASCADE;")
    # Drop index only if it exists to avoid errors if already missing
    op.execute("DROP INDEX IF EXISTS checkpoints_thread_id_idx;")
    # op.drop_index("checkpoints_thread_id_idx", table_name="checkpoints")
    op.execute("DROP TABLE IF EXISTS checkpoints CASCADE;")
    # Drop index only if it exists to avoid errors if already missing
    op.execute("DROP INDEX IF EXISTS checkpoint_blobs_thread_id_idx;")
    # op.drop_index("checkpoint_blobs_thread_id_idx", table_name="checkpoint_blobs")
    op.execute("DROP TABLE IF EXISTS checkpoint_blobs CASCADE;")
    op.add_column(
        "questions",
        sa.Column(
            "feedback_embedding",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
            comment="Embedding vector for the feedback text using text-embedding-ada-002",
        ),
    )
    # ### end Alembic commands ###

    logger.info(f"Completed Add feedback_embedding to questions table upgrade")


def downgrade() -> None:
    """Downgrade schema."""
    logger.info(f"Starting Add feedback_embedding to questions table downgrade")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "feedback_embedding")
    op.create_table(
        "checkpoint_blobs",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "channel",
            "version",
            name="checkpoint_blobs_pkey",
        ),
    )
    op.create_index(
        "checkpoint_blobs_thread_id_idx",
        "checkpoint_blobs",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "checkpoints",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "parent_checkpoint_id", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_ns", "checkpoint_id", name="checkpoints_pkey"
        ),
    )
    op.create_index(
        "checkpoints_thread_id_idx", "checkpoints", ["thread_id"], unique=False
    )
    op.create_table(
        "checkpoint_migrations",
        sa.Column("v", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("v", name="checkpoint_migrations_pkey"),
    )
    op.create_table(
        "checkpoint_writes",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("idx", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "task_path",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "checkpoint_id",
            "task_id",
            "idx",
            name="checkpoint_writes_pkey",
        ),
    )
    op.create_index(
        "checkpoint_writes_thread_id_idx",
        "checkpoint_writes",
        ["thread_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    logger.info(f"Completed Add feedback_embedding to questions table downgrade")
